### ISSUE TITLE
Inability to use texture slots other than 0 on hardware assisted sprites

### ISSUE THREAD

**Issue by DragonMinded** [DragonMinded/libdragon#1]
Haven't really looked into this one.  Might be more of an issue of fitting more than one item in TRAM properly.  Haven't tried giving a sprite a nonzero texture slot ID without adding additional sprites.  I think the reason that multiple slots doesn't work is that the RDP is up converting the texture on copy to the output format and so the offset returned by the original copy function is wrong and thus corrupts the first sprite when you copy the second.  I'll have to look into that theory in the future.

**Comment by rasky** [comment]
Fixed in the [unstable branch](https://github.com/DragonMinded/libdragon/wiki/Unstable-branch) where the new rdpq library exposes this functionality.
