### ISSUE TITLE
Default branch renamed to trunk

### ISSUE THREAD

**Issue by DragonMinded** [DragonMinded/libdragon#106]
I've renamed the default branch to trunk. This had the side effect of closing the two open pull requests, please re-open them. To update your local branch pointers, run the following:

```
$ git checkout master
$ git branch -m master trunk
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/trunk
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/trunk
```

**Comment by networkfusion** [comment]
Not sure I see the point... the "trunk" seems to have lost all check-ins for the last year! I hope someone has an up-to-date fork... (BTW, dont get me started on the meaning of "master").

**Comment by anacierdem** [comment]
Yes this is a really old version @DragonMinded

**Comment by anacierdem** [comment]
I can try to force push the last known good if I’m allowed?

**Comment by networkfusion** [comment]
Since I forked for my very recent PR... the code is still here: https://github.com/networkfusion/libdragon

**Comment by anacierdem** [comment]
I also have a reference in the docker repo -> https://github.com/DragonMinded/libdragon/tree/3c91d3219b3bdf88693a66053d88f1be911b43cd

**Comment by DragonMinded** [comment]
How the hell is renaming a branch possible to blow away a year's worth of commits? Git is truly trash. Sorry for the churn, I am not even sure how its possible to do that sort of thing.

By the way, if you want to "get started" on the meaning of "master" you will be banned from this repo. I already deleted one comment, I won't hesitate to do it again.

**Comment by anacierdem** [comment]
You may have accidentally renamed your old working copy without a pull and force pushed that one, that is the most plausible explanation.

**Comment by DragonMinded** [comment]
I didn't force push, I wouldn't do that on a public repo with any forks/pull requests.

**Comment by DragonMinded** [comment]
Go ahead and force push the last good commit, to trunk. It won't let me check out the commit on my end for some reason.

**Comment by anacierdem** [comment]
No, probably created trunk on an old commit, that was my bad. Not on a computer right now, will do tomorrow 👍🏼

**Comment by DragonMinded** [comment]
Thanks! Sorry again for the bullshit, it should NOT be possible to blow away a year's worth of work in a public repo like this.

**Comment by DragonMinded** [comment]
Ah, I was able to push it myself, don't know why git would *NOT* let me check out the revision linked above but I pulled the branch back from the other fork linked here.

**Comment by anacierdem** [comment]
Renaming a branch effectively deletes the old one and creates the new AFAIK, so it is risky on a public branch indeed. Why did you really decide to rename it?

**Comment by DragonMinded** [comment]
To get rid of explicitly exclusive language on the project.

**Comment by anacierdem** [comment]
Master as a branch name was really something I will never interpret in another context. TIL such a thing existed.

**Comment by anacierdem** [comment]
We may also need to update the build badge and other text references in the project.

**Comment by DragonMinded** [comment]
I don't think travis needs updating, it seems to take the default branch from github and is working fine: https://travis-ci.org/github/DragonMinded/libdragon/branches

**Comment by DragonMinded** [comment]
I updated a few lingering comments and the badge picture itself, but it looks like everything is basically just working.

**Comment by rasky** [comment]
Is there anything actionable here? Can this be closed?

**Comment by DragonMinded** [comment]
It was left open as an announcement, since github has no way of pinning information relevant to but not directly checked into code. It can be closed now.
