### ISSUE TITLE
Potential offset issues with n64tool?

### ISSUE THREAD

**Issue by ghost** [DragonMinded/libdragon#114]
I read from someone that there may be issues with how offsets are handled with n64tool. This person seems rather frustrated at the moment, and I don't want to start any drama, but I will copy and paste verbatim what they said and leave at your discretion how to handle it. If there are issues, I think it's best you know about them. In any case, this is what was said:

Message 1:
> Not unconvinced that n64tool bundled with libdragon has some bugs that only show up if you use it to append multiple files at different offsets and maybe it doesnt get used that way too often because people just use DFS? I dont know. Cant use DFS for Doom, probably nobody was around for that but
>1) file size maxes out at 16M which means no TNT or Plutonia
>2) it has to start from 0 every time to seek or read and go through lists to get to the data you want and this leads to slowdown at boot and during game. Takes 2 to 5 minutes just to get to title screen, more time for game itself, and then it freezes while playing when doing file access
>All of that is to say I'm about to code my own replacement

Message 2:
>Yeah so apparently I havent been using good samples for the last 6 years because I was fighting bugs in libdragon n64tool. Spent 20 minutes rolling my own and everything works as expected. Extremely annoyed about that.
>I'm not going to rewrite their shit for them so I'm not filing any issues or PRs against it

Message 3:
>I have a drop-in replacement for n64tool except mine actually works 🙄
>No error handling though so if you pass things in wrong order it dies
>But that's not far from the way the "real" one works

Message 4:
>here's my n64tool, if you follow the exact argument ordering required for the real one, this will do what you actually expect it to do based on reading the usage details and not fuck up padding and offsets or throw an error message like the libdragon one 🙄
>I'm not going so far as to make it production ready but also not gonna be a completely selfish dick so that's why I figured it's at least here, I dont do discords or forums or anything really because then people make demands and I'm too old and miserable to be polite lol
>Also mine has hardcoded assumptions about the size unit for padding the output file, always "M", and for the offsets to include data from files (-s) it always assumes "B"

Again, not trying to start drama, and I ask that no one attempt to start any either; just wanted to inform you of the possible issues. I've attached the replacement n64tool.c in a zip file below.
[n64tool.c.zip](https://github.com/DragonMinded/libdragon/files/5797776/n64tool.c.zip)

**Comment by DragonMinded** [comment]
This isn't really a useful bug report in any means, its more of a rant. Of course there are going to be bugs, this is an open source amateur toolchain written by me when I was in college a decade ago for fun. I appreciate you trying to bring issues to light, but this person is a douchebag with a bad attitude. This is an unfunded hobby project for a dead, undocumented system.  What, honestly, do they expect? I super do not appreciate how entitled they are in expecting bug-free software for free from somebody they are unwilling to communicate with or give back to. He or she is welcome to rewrite everything in a huff and piss in the wind, I don't have time for angry rants like this and I don't think its fair to push abusive behavior like that on anyone else donating their time to the project.

**Comment by ghost** [comment]
My apologies; I know it's frustrating to have someone shit on your work for no reason. I certainly didn't mean to bring down your day by being the messenger, I just figured if there are problems, maybe somewhere in his rant was something of use. I'm sadly not as knowledgeable to be able to help myself; I can only assure you I had good intentions and I apologize again. For the record, I completely agree with you on this. This was kinda uncharacteristically selfish of this person. I appreciate the work that was put into libdragon and continues to be put in it.

**Comment by DragonMinded** [comment]
Oh, no hate directed at you and I don't think you need to apologize. I just find that if I am not firm with protecting my own time and humanity, people like that guy will shit all over me while expecting me work tirelessly for them. I've been doing homebrew for like 15 years now and there's a ton of dudes like him and its best to nip that sort of behavior in the bud.
