### ISSUE TITLE
Try not saving registers for interrupts

### ISSUE THREAD

**Issue by anacierdem** [DragonMinded/libdragon#129]
Current interrupt handler saves and restores gp/fp registers on entry end restores them on exit except for `k0` and `k1`, which do not require saving. Theoretically it should be possible to skip; `s0-s7`, `gp`, `sp`, `ra`, and `f21-f31` as MIPS calling convention stipulates that they are saved on function pro/epilogues when necessary. GCC seem to complyas some experimentation shown that they are indeed saved in disassembled output. On the other hand we had issues with fp registers (causing unimplemented exceptions where they seem to be loaded from `s0-s7`). Also a test benchmark was failing without them being saved, although I couldn't verify if it is directly related.

We may work on this further in the future.

**Comment by rasky** [comment]
> On the other hand we had issues with fp registers (causing unimplemented exceptions where they seem to be loaded from s0-s7)

For posterity, this turned out to be unrelated.
