### ISSUE TITLE
Are example roms supposed to run in an emulator?

### ISSUE THREAD

**Issue by derselbst** [DragonMinded/libdragon#14]
Hi,

i am trying to get into n64 dev. I followed the steps in the readme and compiled the example roms. However, in my case they dont run in an emulator (tried mupen64plus and nemu64). Are they supposed to do so?

**Comment by wareya** [comment]
You won't have any luck with HLE emus. That said, nemu64 runs *some* libdragon homebrew, but it's certainly not too much.

**Comment by derselbst** [comment]
Ok, and which one(s) should run in nemu64?

In case of mupen64plus I ran it in pure interpreter mode and used z64 as rsp plugin (which is as far as I know a LLE plugin)... but it crashed with SEGV anyway

**Comment by DragonMinded** [comment]
Mess actually does proper LLE and runs almost all of libdragon's roms. I did a lot of testing using it.

**Comment by derselbst** [comment]
Got it working. Thanks for the hint!

**Comment by LavenderMoon** [comment]
I can't get MAME to respond to any of my button presses in the libdragon examples. MAME worked with Super Smash Brothers, and I got the libdragon examples to run on my actual N64. MESS 0.161, the last standalone version, does handle input, however.

**Comment by DragonMinded** [comment]
Not terribly surprised. I haven't tinkered with MAME since the MESS merge, but I'd assume it shouldn't be broken. Your mileage may vary though. Has anyone else had success?

**Comment by DeclanHoare** [comment]
MAME 0.172 is the only version compatible with libdragon as far as I can tell.  <=0.171 timers do not work, 0.173 crashes on startup, >=0.174 input does not work.
