### ISSUE TITLE
recurse_path hangs trying to open file.

### ISSUE THREAD

**Issue by giulianobelinassi** [DragonMinded/libdragon#141]
Adapting the spritemap example about how to create an dfs filesystem on a different project, the function `dfs_open()` hangs on an infinite loop when executing `recurse_path`.

Even if I did something wrong (i.e., failed to initialize the dfs or it wasn't properly created), it should never hang on an infinite loop there. An error should be returned.

[edit]
The cause of the issue is `dfs_init()` failing to initialize the dfs, probably because the dfs offset is incorrect. How can I know exactly where the filesystem is located in memory?

**Comment by rasky** [comment]
`dfs_init()` does return an error. We can add an assert on all dfs functions if `dfs_init()` wasn't successfully called, but in general if error values are not checked when returned, it's hard to make sure that you never see a hang.

The address of the filesystem depends on the offset you specify when calling n64tool. Normally it's `DFS_DEFAULT_LOCATION`.

**Comment by giulianobelinassi** [comment]
In comments of dragonfs.c, it reads:

```
/**
 * @brief Initialize the filesystem.
 *
 * Given a base offset where the filesystem should be found, this function will
 * initialize the filesystem to read from cartridge space.  This function will
 * also register DragonFS with newlib so that standard POSIX file operations
 * work with DragonFS.
 *
 * @param[in] base_fs_loc
 *            Memory mapped location at which to find the filesystem.  This is normally
 *            0xB0000000 + the offset used when building your ROM + the size of the header
 *            file used.
 *
 * @return DFS_ESUCCESS on success or a negative error otherwise.
 */
```
This means that if I create a ROM with:

`n64tool -l 2M -t "TD" -h /usr/local/mips64-elf/lib/header -o td.z64 td.bin -s 1M cdrom.dfs`

Where `cdrom.dfs` is a simple copied spritemap.dfs from the spritemap example, I should get an offset of:

`0xB0000000 + 0x00100000 + 0x00001000 = 0xB0101000`

Where 0xB0000000 is the base address, 0x00100000 is the 1M size passed as -s argument, and 0x00001000 = 4096, which is the size of the header in bytes. The sum equals `DFS_DEFAULT_LOCATION`, as defined in dragonfs header.

However, calling`dfs_init(DFS_DEFAULT_LOCATION)` results in an initialization error on my application. Hooking GDB to cen64 in my application, 0xB0101000 points to 0x402025. Looking for the same pointer in the spritemap and dfsdemo examples, the 0xB0101000 points to 0xdeadbeef.

Therefore, there seems to be other parameters that takes account in determining the location pointer. How where this 0xB0000000 base address determined?

**Comment by giulianobelinassi** [comment]
I found that the DFS address was allocated on `0xB01A7900` on my project by searching for the hexadecimal value "DE AD BE EF" on the .z64 ROM file with an Hex Editor.

There seems to be an 1 to 1 map between the ROM and the adresss 0xB0000000.  This means that accessing 0xB01A7900 on Nintendo 64 is the same thing as reading the bytes at 0x001A7900 on the ROM file. The reason why this address was allocated in 1A7900 is still a mistery to me.

However, this seems a consistent way of finding the filesystem address. I can patch n64tool so that it can print this address when building the .z64 file.

**Comment by rasky** [comment]
> Where 0xB0000000 is the base address, 0x00100000 is the 1M size passed as -s argument, and 0x00001000 = 4096, which is the size of the header in bytes. The sum equals DFS_DEFAULT_LOCATION, as defined in dragonfs header.

Correct. It's probably counterintuitive that the offset specified with `-s` does not include the header, but we're too late to revert that decision.

> However, callingdfs_init(DFS_DEFAULT_LOCATION) results in an initialization error on my application. Hooking GDB to cen64 in my application, 0xB0101000 points to 0x402025. Looking for the same pointer in the spritemap and dfsdemo examples, the 0xB0101000 points to 0xdeadbeef.

Even without gdb, you can simply use `debugf("%08lx\n", *(uint32_t*)DFS_DEFAULT_LOCATION)` (after `debug_init_isviewer()` and running cen64 with `-is-viewer`).

> There seems to be an 1 to 1 map between the ROM and the adresss 0xB0000000. 

Yes, this is how the N64 memory map works. The ROM is mapped at `0x10000000` in the memory space, you can consult any documentation online on the N64 memory map.

The top 3 bits are actually special bits in MIPS CPU addressing that specify whether to use the cache or not, and whether the address is virtual of physical. In this case with `0xA` we're asking for physical uncached address (see also the `UncachedAddr` macros in libdragon).

> I found that the DFS address was allocated on 0xB01A7900 on my project by searching for the hexadecimal value "DE AD BE EF" on the .z64 ROM file with an Hex Editor.

If you pass `-s 1M` to `n64tool`, you should get the filesystem ad `DFS_DEFAULT_LOCATION`. If not, there is a bug somewhere (or a missing error?). I'd love if you get add some prints to n64tool to find out what's going on. Or if your code is published somewhere, I can help you debugging this.

**Comment by giulianobelinassi** [comment]
> If you pass -s 1M to n64tool, you should get the filesystem ad DFS_DEFAULT_LOCATION. If not, there is a bug somewhere (or a  missing error?). I'd love if you get add some prints to n64tool to find out what's going on. Or if your code is published somewhere, I can help you debugging this.

I think the issue is related to the code size, as I was near the 2M when this was happening and now with almost 4M of code and adding more files to the filesystem, the problem vanished. Although now I use 4M of filesystem size and, as expected, is falls into `0xB0401000`. Maybe the most reliable way is to, indeed, make n64tool print the dfs address so the programmer can update its address in the code.

The project that I am working on is Vanilla Conquer, trying to port it to N64. I am not sure how far I would get into porting this, but I know that it is possible because this game was already (poorly) ported to the N64 in 1999.

Repository: https://github.com/giulianobelinassi/Vanilla-Conquer/tree/n64

**Comment by rasky** [comment]
Thanks, I realized the bug is that there is no error check that a DFS image cannot be put at the requested offset. For now, it's better to simply error out and let the user change the offset specified with `-s` (since they also need to change the call to `dfs_init()` accordingly). 

In the future we might look into automating all this; for instance, `n64tool` could record the offset in the header so that `dfs_init()` automatically locate the filesystem. But I would say that for now the bug fix is sufficient to avoid the error you saw.
