### ISSUE TITLE
Travis checks are not running

### ISSUE THREAD

**Issue by anacierdem** [DragonMinded/libdragon#157]
They don't seem to be enabled at the moment. @DragonMinded needs to check this one to make sure it is properly configured.

**Comment by DragonMinded** [comment]
I went to check out why they got disabled and it looks like Travis CI kinda sucks now? They don't have any record of this repository, and when I try to activate it for this repo they are telling me they need a credit card to enable the free version. Yeah right. Is there another CI software that isn't so hostile to FOSS stuff?

**Comment by anacierdem** [comment]
I also went through that for my own pojects and just quit Travis. Good news is that we have already enabled Github Actions :)

**Comment by DragonMinded** [comment]
Okay, so what if anything do I need to do on my side to make it work? I was reading a bit and it looks like github actions is the way to go now.

**Comment by anacierdem** [comment]
No, you won't need to do anything. I have tried to ping you on #175 but then we decided to merge it.

**Comment by DragonMinded** [comment]
Oh yeah I didn't get those pings sorry. IDGAF about the token use, seems fine to me. So CI is working again and we can close this task?
