### ISSUE TITLE
Breakage: C projects can no longer link libdragon using LD

### ISSUE THREAD

**Issue by meeq** [DragonMinded/libdragon#200]
I updated FlappyBird to fix breakages in the latest libdragon trunk, was able to build after #199 but when I run the resulting ROM I get:

![image](https://user-images.githubusercontent.com/11916110/138181870-517da66d-9c5e-4264-b6f0-e973ac064c3a.png)

This means that all existing projects using C and libdragon who have not updated to n64.mk will start producing broken builds. If debug is on, there will at least be the assertion error, but there is no indication at compile-time that anything is awry.

**Comment by anacierdem** [comment]
@meeq Can you please verify the PR is fixing the problem?
