### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by vgturtle127** [DragonMinded/libdragon#21]
There isn't currently a license in the repo.

Mentioning the license in the readme might be a good idea as well.

**Comment by DragonMinded** [comment]
I'm pretty sure I threw it out as public domain, honestly. A more permissive license is preferred, I am not particularly fond of restrictive licenses such as GPL.

**Comment by bentley** [comment]
Current copyright law is all rights reserved, so if you (the copyright holder) don’t specifically allow redistribution, modification, etc., the license is restrictive by default. If you want it to be public domain, please state so in the repo.

I love the public domain, but there are some problems with attempting to license software under it (i.e., doing that may not have the effect you want). For example, not all countries allow abandoning your copyrights, so people in those countries won’t be able to use your public domain software (dumb, I know). I usually go with the [ISC license](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/share/misc/license.template?rev=1.3&content-type=text/x-cvsweb-markup); it’s one sentence long plus warranty disclaimer.

**Comment by vgturtle127** [comment]
You could use the unlicense, or you could use the MIT/BSD/ISC licenses which are very permissive.

http://unlicense.org/
http://opensource.org/licenses/MIT
http://opensource.org/licenses/isc-license
http://opensource.org/licenses/BSD-2-Clause
http://opensource.org/licenses/BSD-3-Clause
