### ISSUE TITLE
Activate GitHub Pages

### ISSUE THREAD

**Issue by rasky** [DragonMinded/libdragon#217]
Hi @DragonMinded, we would like to begin publishing updated Doxygen documentation. We've setup a CI job on GitHub Actions and the easiest option would be to use GitHub Pages. Would you mind activating it for this repository?

**Comment by DragonMinded** [comment]
I clicked activate, looks like its here: http://dragonminded.github.io/libdragon/

**Comment by rasky** [comment]
Thank you!

**Comment by rasky** [comment]
@DragonMinded can you please change the configuration to use the `gh_pages` branch instead of `trunk`? Root folder is fine.

**Comment by DragonMinded** [comment]
Done.

**Comment by rasky** [comment]
Thank you! Last thing in this area: the "about" section of the repository shows a link to http://www.dragonminded.com/n64dev which has outdated contents. Would you mind changing that link to the new website? We configured a custom domain for it: https://libdragon.dev so that it's shorter and easier to google.

**Comment by DragonMinded** [comment]
Done.

**Comment by rasky** [comment]
Thank you!
