### ISSUE TITLE
Empty folder on mkdfs causes error.

### ISSUE THREAD

**Issue by stefanmielke** [DragonMinded/libdragon#240]
Using mksprite on a folder that has a folder without anything on it causes it to fail.

Ideally it should just not import that folder, or answer with a message telling the user that it doesn't support empty folders.

Output sample (with an empty folder inside `build/filesystem`):
```
/n64_toolchain/bin/mkdfs build/test.dfs build/filesystem
Error creating filesystem.
```

**Comment by rasky** [comment]
Fixed by #268
