### ISSUE TITLE
permission error 

### ISSUE THREAD

**Issue by mixotricha** [DragonMinded/libdragon#251]
I am building the : 

https://github.com/snacchus/libdragon branch 

_but_ I think what I am getting is a general error rather than error specific to that branch. 

Someway through build-toolchain.sh I am getting : 

make[4]: Entering directory '/home/mixotricha/workspace/n64/opengl_test/libdragon/build/binutils-2.37/bfd/doc'
 /bin/mkdir -p '/usr/local/share/info'
 /usr/bin/install -c -m 644 ./bfd.info '/usr/local/share/info'
/usr/bin/install: cannot remove '/usr/local/share/info/bfd.info': **Permission denied**
make[4]: *** [Makefile:826: install-info-am] Error 1
make[4]: Leaving directory '/home/mixotricha/workspace/n64/opengl_test/libdragon/build/binutils-2.37/bfd/doc'
make[3]: *** [Makefile:1643: install-recursive] Error 1
make[3]: Leaving directory '/home/mixotricha/workspace/n64/opengl_test/libdragon/build/binutils-2.37/bfd'
make[2]: *** [Makefile:1751: install] Error 2
make[2]: Leaving directory '/home/mixotricha/workspace/n64/opengl_test/libdragon/build/binutils-2.37/bfd'
make[1]: *** [Makefile:2883: install-bfd] Error 2
make[1]: Leaving directory '/home/mixotricha/workspace/n64/opengl_test/libdragon/build/binutils-2.37'
make: *** [Makefile:2338: install] Error 2

Note that I have built the LibDragon standard branch successfully previously and also the tools and examples and they run fine with that branch. 

Hope this is sufficient context and useful.

**Comment by meeq** [comment]
It looks like your N64_INST is not set properly, as it is trying to install to `/usr/local/share` (which is usually undesirable).

Make sure you `export N64_INST=$HOME/Projects/n64/toolchain` (or wherever you want the toolchain to be installed)

**Comment by mixotricha** [comment]
Thank you! And of course I did set that when I built the main branch to which is why it successfully built. Problem solved.
