### ISSUE TITLE
Issue in makefile

### ISSUE THREAD

**Issue by MS-DOS1999** [DragonMinded/libdragon#29]
when i type "make" after ./build, i have an error like this : "error command not found bin/mips64-elf-gcc " so i have change this line in makefile : "N64PREFIX = $(N64_INST)/bin/mips64-elf-" to "N64PREFIX = $(N64_INST)/usr/local/bin/mips64-elf-" and "INSTALLDIR = $(N64_INST)" to "INSTALLDIR = $(N64_INST)/usr/local/" and it work with it.

**Comment by sp1187** [comment]
You need to set the environment variable `N64_INST` to `/usr/local`. You can for example include it directly in the command with `N64_INST=/usr/ make` or define it in advance with the command `export N64_INST=/usr/local`.

**Comment by MS-DOS1999** [comment]
Ok thanks :)

**Comment by anacierdem** [comment]
Closing this one due to inactivity. Seems resolved already.
