### ISSUE TITLE
Removing old doxygen site

### ISSUE THREAD

**Issue by rasky** [DragonMinded/libdragon#343]
Hi @DragonMinded, now that we update docs via CI on GitHub pages (libdragon.dev), the doxygen on dragonminded.com is a stale copy, which is though quite well indexed on Google. Would it be possible to either remove it or add a redirect to the new one? It happens from time to time that people get confused by reading the old docs that are somehow misaligned with the code now.

**Comment by DragonMinded** [comment]
Updated~
