### ISSUE TITLE
Timers are not called if the ticks value is "too small"

### ISSUE THREAD

**Issue by Dragorn421** [DragonMinded/libdragon#359]
This was tested on hardware

Consider the simple rom:
```c
#include <libdragon.h>

// set to 1 when the timer callback runs
volatile int timer_i = 0;

void timer_callback(int ovfl)
{
    timer_i = 1;
}

int main(void)
{
    display_init(RESOLUTION_320x240, DEPTH_16_BPP, 2, GAMMA_NONE, ANTIALIAS_RESAMPLE);
    timer_init();

    // have timer_callback called every 1000 ticks
    new_timer(1000, TF_CONTINUOUS, timer_callback);

    int i = 0; // frame counter, mostly to make sure something is happening

    // increment i, and display i and timer_i on screen, every frame
    while (1)
    {
        i++;

        surface_t *surf;
        while ((surf = display_lock()) == NULL)
            ;

        graphics_fill_screen(surf, graphics_make_color(0, 0, 0, 0));

        char buf[100];
        snprintf(buf, sizeof(buf), "i=%d  timer_i=%d", i, timer_i);
        graphics_draw_text(surf, 10, 50, buf);

        display_show(surf);
    }
}
```
as expected this results in `timer_i=1` since `timer_callback` is run 1000 ticks or so after boot:
![image](https://user-images.githubusercontent.com/5306619/224842544-9f74f44a-e821-4066-b8f1-52f7044d268b.png)

However if 1000 is changed to 1 (for example) (i.e. `new_timer(1, TF_CONTINUOUS, timer_callback);`) then it stays `timer_i=0`, indicating the timer callback never runs (note: `i` keeps incrementing)

![image](https://user-images.githubusercontent.com/5306619/224843036-c06e6c43-594b-46a6-b56e-bd3ac088b778.png)

Same thing with `TF_ONE_SHOT` instead of `TF_CONTINUOUS`.

Some limited testing shows 100 (`new_timer(100, TF_CONTINUOUS, timer_callback);`) doesn't run the callback but 200 does

**Comment by rasky** [comment]
What would be the expected behavior? 

If you specify a value that's lower than the timer callback processing time (including overhead) there are basically two options: we either ignore it (like we do now), or respect it and go into infinite loop where as soon as we exit an interrupt we must retrigger it.

**Comment by Dragorn421** [comment]
I would expect continuous/one-shot timers to run as soon/quick as possible

For continuous timers, it would mean I would expect a "freeze" from the timer interrupt not giving the cpu any chance to do anything useful
In that case it may be better to abort when a low-period continous timer is started

For one-shot timers, I do think it would make sense that the timer just runs as soon as possible, since it seems like a valid use case, for example imagine some code computes the ticks to wait until the next event and just happens to compute 100 ticks, then the timer never executing would be quite problematic

--------

Suggested fixes (various ideas):

- At the very least mention in the docs that low ticks period values should be avoided (timers wouldn't run)
- abort when a small ticks value is used
- use max(ticks, 10000) instead of the provided ticks in the new_timer function
- have new_timer explicitly able to fail to start a timer, and fail to start a timer when the ticks value is low (but I'm not a fan because it leaves error checking to the user)
- allow the user to choose among the above:
  ```c
  timer_link_t* new_timer(int ticks, int flags, timer_callback1_t callback);
  ```
  ->
  ```c
  enum timer_check_mode {
  TCM_NONE, // don't check the timer ticks value, timer may not run if ticks too small
  TCM_CLAMP, // use max(ticks, 10000), "guarantees" (?) the timer will run but slower than expected
  ...
  };

  timer_link_t* new_timer_check_ticks(int ticks, int flags, timer_callback1_t callback, enum timer_check_mode checkMode);

  #define new_timer(ticks, flags, callback) new_timer_check_ticks(ticks, flags, callback, TCM_NONE)
  ```
  Or add those to timer flags (TF_) instead idk
