### ISSUE TITLE
[opengl] `glGenLists(0)` should return 0

### ISSUE THREAD

**Issue by Dragorn421** [DragonMinded/libdragon#386]
`glGenLists(0)` doesn't return 0 but the would-be next index:
https://github.com/DragonMinded/libdragon/blob/f8143d4f42e0fbb0fa9e749c64a26db58fd0cae4/src/GL/list.c#L202-L209

# Reference

http://www.glprogramming.com/red/chapter07.html
> GLuint glGenLists(GLsizei range);
>     ... Zero is returned if the requested number of indices isn't available, or if range is zero. 

https://registry.khronos.org/OpenGL/specs/gl/glspec11.pdf
> GenLists returns 0 if there is no group of s contiguous previously unused display list indices, or if s = 0

**Comment by snacchus** [comment]
This issue was fixed in edf09b2
