### ISSUE TITLE
[opengl] `gl_context_end`'s asserts may be misplaced

### ISSUE THREAD

**Issue by Dragorn421** [DragonMinded/libdragon#387]
I asked about the asserts in `gl_context_end`
https://github.com/DragonMinded/libdragon/blob/3be205ec853257162fb3bbf334f311cdd33808ce/src/GL/gl.c#L192-L197

and @rasky mentioned these may be misplaced now ( https://discord.com/channels/205520502922543113/974342113850445874/1124940607178162236 )

**Comment by rasky** [comment]
Fixed by #494
