### ISSUE TITLE
[opengl] libdragon's `immediate_active` boolean is unrelated to what opengl calls "immediate"

### ISSUE THREAD

**Issue by Dragorn421** [DragonMinded/libdragon#388]
libdragon calls `immediate_active` the boolean it uses for "is inside a glBegin/glEnd block"

But that seems to be a different meaning than what opengl calls "immediate":
http://www.glprogramming.com/red/chapter01.html
> All data, whether it describes geometry or pixels, can be saved in a display list for current or later use. (The alternative to retaining data in a display list is processing the data immediately - also known as *immediate mode*.) When a display list is executed, the retained data is sent from the display list just as if it were sent by the application in immediate mode.

https://registry.khronos.org/OpenGL/specs/gl/glspec11.pdf
> For the most part, OpenGL provides an immediate-mode interface, meaning that specifying an ob ject causes it to be drawn.

It seems to have more to do with '"writing a dlist" vs "issue graphical commands immediately"',
than 'is an object being drawn'.

-----

As to how references refer to "glBegin/glEnd block":

http://www.glprogramming.com/red/chapter02.html
> void glBegin(GLenum mode);
>     Marks the beginning of a vertex-data list that describes a geometric primitive.
> void glEnd(void);
>     Marks the end of a vertex-data list.
-> "vertex-data list" but this is not used anywhere in the spec

and the spec uses "begin/end object", "begin/end pair", "begin and end pair".

So there's not really proper terminology besides begin/end -based unfortunately.

**Comment by rasky** [comment]
Fixed by #494
