### ISSUE TITLE
Clarify license terms for n64.ld

### ISSUE THREAD

**Issue by fsomers** [DragonMinded/libdragon#399]
(follow-on from DMs with rasky)

I authored the original version of n64.ld, a ...long... time ago.

There was no licence file distributed with the original "release", and at the time I was not concerned with license terms - it was meant to be in a similar spirit to the goals for libdragon  - note the following extract from the start of the `readme.txt` that was part of the original release:
```
So you want to code for the N64.... 
And you've been looking for a legitimate and freely available development system you could use... 
We did... We've put together one, and here it is!
```

I am completely fine with stating that any g0dev parts which may remain (noting the original version of `n64.ld`) can be included and treated as though they are unencumbered, and can be licensed under this project's license: https://github.com/DragonMinded/libdragon/blob/trunk/LICENSE.md

**Comment by rasky** [comment]
Thanks @fsomers, much appreciated! I will now clarify the license terms in the file.
