### ISSUE TITLE
[opengl] `glCurrentPaletteMatrixARB` range check error message off by 1

### ISSUE THREAD

**Issue by Dragorn421** [DragonMinded/libdragon#406]
https://github.com/DragonMinded/libdragon/blob/4409fe77e208aaef77800b684602d4ea5a74da0b/src/GL/matrix.c#L158-L159

but the allowed values are 0 to `MATRIX_PALETTE_SIZE-1` (inclusive)

I think it should be either
`[0, %d))", index, MATRIX_PALETTE_SIZE);`
or
`[0, %d])", index, MATRIX_PALETTE_SIZE-1);`

**Comment by rasky** [comment]
Fixed by #494
