### ISSUE TITLE
[opengl] gldemo Assertion failed: Unexpected RDP interrupt

### ISSUE THREAD

**Issue by willthehuman** [DragonMinded/libdragon#423]
<img width="1447" alt="Screenshot 2023-08-26 at 10 45 09" src="https://github.com/DragonMinded/libdragon/assets/38778465/1af093f9-aefe-42b5-9b45-9c4e1e170882">

Steps to reproduce : 

1. Install libdragon cli using docker
2. cd to the gldemo
3. libdragon make
4. Run the rom

- Hardware : Macbook Pro M1 Pro 14"
- MacOS Ventura 13.4.1
- RetroArch 1.15.0 - Mupen64Plus-Next (2.5-Vulkan 26fd1ed)

**Comment by rasky** [comment]
Mupen64plus is an old emulator which is not accurate enough to run libdragon. It does not faithfully emulate the hardware.

At the moment, the only emulator that is accurate enough to reliably run libdragon is Ares. Simple64 is very good too, but alas not all libdragon games/demos run with it.
