### ISSUE TITLE
Love the Logo!

### ISSUE THREAD

**Issue by DragonMinded** [DragonMinded/libdragon#431]
Whoever made the logo for libdragon, you absolutely made my whole weekend. What a nice surprise to see when I visited to see what's new and to send a link a friend! Also, I know I'm not involved in this anymore, but it's really nice to come back occasionally and see that the project is flourishing. Thanks so much for being good stewards to a library that was near and dear to my heart and I'm still very proud of, and thank you for proving that even with public domain code, so many will give back and make something cool!

Sorry to open an issue (though I feel like I'm allowed to do that on my own GitHub ;P), but I don't know of any other way to communicate to the project.

**Comment by SpookyIluha** [comment]
> Whoever made the logo for libdragon, you absolutely made my whole weekend. What a nice surprise to see when I visited to see what's new and to send a link a friend! Also, I know I'm not involved in this anymore, but it's really nice to come back occasionally and see that the project is flourishing. Thanks so much for being good stewards to a library that was near and dear to my heart and I'm still very proud of, and thank you for proving that even with public domain code, so many will give back and make something cool!
> 
> Sorry to open an issue (though I feel like I'm allowed to do that on my own GitHub ;P), but I don't know of any other way to communicate to the project.

Thank you so much for noticing the team effort behind both the new Libdragon logo and Libdragon itself (both trunk and unstable branches)
If you'd like to know more about logo's development or to see in real-time how the sdk is developed, there's a libdragon discord channel in a N64brew discord server you can check out!

Logo wiki page: https://github.com/DragonMinded/libdragon/wiki/Logos
How the logo was developed: https://discord.com/channels/205520502922543113/1122923935349100665
Libdragon project channel: https://discord.com/channels/205520502922543113/974342113850445874
