### ISSUE TITLE
Unable to run basic project in any emulator

### ISSUE THREAD

**Issue by kinderhead** [DragonMinded/libdragon#454]
I created a basic project using the libdragon cli, but I am having trouble running the examples and project. I cannot run them in any of the suggested emulators in the README or any other conventional emulator. Thanks.

**Comment by rasky** [comment]
Hello, the supported emulators are written in the README.

Libdragon is meant to run on real hardware and use as much as possible of hardware features. Modern, accurate emulators like Ares and simple64 will not have many problems running libdragon roms, while old emulators normally are not accurate enough.

**Comment by rasky** [comment]
Sorry maybe I misread: if you tried with the latest version of Ares and they don’t run, please provide a build log and upload the whole build folder of an example (eg: timers) so that we can check what’s going on.
