### ISSUE TITLE
wait_ms not working

### ISSUE THREAD

**Issue by anacierdem** [DragonMinded/libdragon#51]
#include <stdio.h>

    #include <libdragon.h>

    int main(void)
    {
        resolution_t res = RESOLUTION_320x240;
        bitdepth_t bit = DEPTH_32_BPP;

        init_interrupts();

        display_init( res, bit, 2, GAMMA_NONE, ANTIALIAS_RESAMPLE );

        console_init();
        console_set_render_mode(RENDER_MANUAL);

        while(1)
        {
            printf("Test");

            wait_ms(1);

            console_render();
        }
    }

This is getting stuck at `wait_ms(1)`.

**Comment by vieux** [comment]
From what I read online, the reg 9 on COP0 is the Processor cycle count, it's increased on each opcode processed by the CPU, is has nothing to do with ticks and time. I'll make a PR to remove/update those functions.
