### ISSUE TITLE
Reading directory contents from sdcard on flash cartdrige

### ISSUE THREAD

**Issue by fhoedemakers** [DragonMinded/libdragon#525]
dfsdemo.c recursively enumerates the directory contents of the rom:// filesystem in a rom. Is it also possible to read directory contents  using sd:// on the sdcard inserted into an everdrive flash cart?
I tried to modify dfsdemo.c, but it cannot read the directory contents from the sd:// . I use an official  Everdrive 64 X7. I have put all the files in the /filesystem folder of the sd-card.
Purpose is to display a menu which displays files and subfolders from the sd:// User can select a file to load or a subdirectory to list.

Maybe i'm doing something wrong.

Frank

**Comment by rasky** [comment]
It is indeed possible using `dir_findfirst` / `dir_findnext`, but I think it's currently buggy on trunk. It should be fixed in the preview branch. I'm merging lots of changes from preview to trunk in these days, I'll touch this issue once it's fixed.

**Comment by rasky** [comment]
Hopefully the fix was merged in the latest merge train.

**Comment by fhoedemakers** [comment]
Thanks again!

**Comment by fhoedemakers** [comment]
Wrote a little test program and it works fine. I can see the contents of the /filesystem folder of my Everdrive on my N64.

````c
#include "libdragon.h"

// Read the contents of the SD card on an Everdrive 64
// Tested on an Everdrive 64 X7
// This code will list all files and directories in the /filesystem folder of the SD card
// Create a folder named "filesystem" on the root of the SD card and put some files in it.
int main() {
    debug_init(DEBUG_FEATURE_LOG_ISVIEWER);
    console_init();
    /* This will initialize the SD filesystem using 'sd:/' to identify it */
   if (!debug_init_sdfs("sd:/", -1)) {
	debugf("Error opening SD\n");
        printf("Error opening SD\n");
        exit(1);
    }
    dir_t dir;
    int err = dir_findfirst("sd:/",&dir);
    int count = 0;
    while( err == 0 ) {
        if (dir.d_type == DT_DIR) {
            printf("[%s]\n", dir.d_name);
        } else {
            printf("%s\n", dir.d_name);
        }
        err = dir_findnext("sd:/", &dir); 
        count++;  
    }
    if (count == 0) {
        printf("No files in this dir...\n");
    }   
}
````

Thanks again!
