### ISSUE TITLE
rdpq_sprite_blit crop doesn't work with flipping

### ISSUE THREAD

**Issue by ghost** [DragonMinded/libdragon#562]
I apologize for not having a minimal repro for this but see the example in https://github.com/kannoneer/libdragon/blob/4521ce1bbee1328ba7022a203e33b3de0c85956b/examples/gameloop/gameloop.c#L111

```c
  rdpq_sprite_blit(player_sprite, player.pos.x, player.pos.y, &(rdpq_blitparms_t){
      .s0 = player.frame * PLAYER_SPRITE_SIZE,
      .width = PLAYER_SPRITE_SIZE,
      .flip_x = player.facing == FACING_LEFT
  });
```

when `.flip_x=true` the sprite is rendered at a wrong location on x axis.

This is the spritesheet I was trying to display:
![ninjafrog](https://github.com/DragonMinded/libdragon/assets/99533466/21bf4ad3-8fb6-4473-94ee-1699661c9862)

**Comment by rasky** [comment]
Fixed on trunk too:
https://github.com/DragonMinded/libdragon/commit/5f7d336711b1eb9c9fbabb583eb70862b822a3aa
