### ISSUE TITLE
libdragon init cant specify directory on windows

### ISSUE THREAD

**Issue by Boxingbruin** [DragonMinded/libdragon#593]
Unexpected behavior: Directory defaults to /Users/{user} no matter what directory specified in the cmd prompt.  

I had to modify project-info.js to my specific directory to get it to initialize somewhere else:

```
async function findLibdragonRoot(
  start = 'C:\\Users\\{user}\\Documents\\N64\\libdragon',
```

Expected behavior:  cmd prompt opened to a specific folder such as C:/Users/{user}/Documents/N64/libdragon should initialize the project in that location.

**Comment by anacierdem** [comment]
Can you please move this issue to https://github.com/anacierdem/libdragon-docker?

There is no way of specifying a different directory but there is an issue for that: https://github.com/anacierdem/libdragon-docker/issues/52

Does that align with your expectations?

**Comment by rasky** [comment]
Closing for now as it should be moved anyway
