### ISSUE TITLE
maxBuffer exceeded exception

### ISSUE THREAD

**Issue by herrkuhn** [DragonMinded/libdragon#67]
When I build libdragon from git according to documentation I get a maxBuffer exceeded exception. Default is 1024 * 1024, I had to set it to 1024 * 1024 * 64 to compile through, 1024 * 1024 * 32 wasn't enough.

```
@@ -16,7 +16,7 @@ const options = {
 
 function runCommand(cmd) {
   return new Promise((resolve, reject) => {
-    const command = exec(cmd, {}, (err, stdout, stderr) => {
+    const command = exec(cmd, {maxBuffer: 67108864}, (err, stdout, stderr) => {
```

That is some pretty hefty increase, is it possible that some default logging parameter was set accidentally?

**Comment by anacierdem** [comment]
There weren't any related change and I have rebuild a base image a month ago with no problems.
Maybe node changed something. Will investigate...
