### ISSUE TITLE
Entrypoint only supports CIC 6102

### ISSUE THREAD

**Issue by anacierdem** [DragonMinded/libdragon#76]
It always uses `0x80000318`. Also see `system.c` which uses both addresses `0xA0000318` and `0xA00003F0`.

**Comment by rasky** [comment]
This is not true anymore in the unstable branch, as libdragon only supported the new open source IPL3, whose API is not CIC-dependent.

**Comment by rasky** [comment]
IPL3 was merged to trunk too, so we now support all CIC types transparently (with the same IPL3).
