### ISSUE TITLE
Separating the javascript and docker wrapper

### ISSUE THREAD

**Issue by anacierdem** [DragonMinded/libdragon#78]
It is becoming another project in itself :) What do you think @DragonMinded if we move `Dockerfile` and javascript stuff elsewhere which will use `DragonMinded/libdragon` as a say git module?

**Comment by DragonMinded** [comment]
Seems reasonable. I'm not worked up either way, the js and docker stuff seemed like a reasonable way to help new people get started. But it does make sense to separate and keep the library separate from a deployment.

**Comment by anacierdem** [comment]
Even I find it useful to just fire aup a new container for a new experiment. Also being able to check the build status was nice. Let's keep this issue for some time in case somebody say something. I will work on a separate repo for deployment when I have the time.

**Comment by anacierdem** [comment]
Opened https://github.com/anacierdem/libdragon-docker, now working on libdragon side.

**Comment by anacierdem** [comment]
Also see https://github.com/anacierdem/libdragon/tree/without-deployment

**Comment by anacierdem** [comment]
I will soon send a PR.
